# lesson1 week2

## 1.用空间复杂度换取时间复杂度

In [4]:
import  numpy as np

a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [24]:
import time #导入时间库
a = np.random.rand(1000000)
b = np.random.rand(1000000) #通过round随机得到两个一百万维度的数组
tic = time.time() #现在测量一下当前时间

#向量化的版本
c = np.dot(a,b)
toc = time.time()
print(c)
print("Vectorized version:" + str(1000*(toc-tic)) +"ms") #打印一下向量化的版本的时间

#继续增加非向量化的版本
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print("For loop:" + str(1000*(toc-tic)) + "ms")#打印for循环的版本的时间

249730.676549846
Vectorized version:0.9915828704833984ms
249730.6765498442
For loop:588.4613990783691ms


## 2.广播机制

In [11]:
import numpy as np
A=np.array([
    [56.0,0.0,4.4,68.0],
    [1.2,102.0,52.0,8.0],
    [1.8,135.0,99.0,0.9]
])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 102.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [12]:
cal=A.sum(axis=0) #axis=0 表示的是竖向相加
print(cal)

[ 59.  237.  155.4  76.9]


In [17]:
print(A/cal.reshape(1,4)) #这里的reshape可加可不加

[[0.94915254 0.         0.02831403 0.88426528]
 [0.02033898 0.43037975 0.33462033 0.10403121]
 [0.03050847 0.56962025 0.63706564 0.01170351]]


In [22]:
B=np.array([
    [1,2,3],
    [4,5,6],
])
C=100
print(B+C)
print("############")
B=np.array([
    [1,2,3],
    [4,5,6],
])
C=[100,200,300]
print(B+C)
print("############")
B=np.array([
    [1,2,3],
    [4,5,6],
])
C=[[100],[200]]
print(B+C)

[[101 102 103]
 [104 105 106]]
############
[[101 202 303]
 [104 205 306]]
############
[[101 102 103]
 [204 205 206]]


## 3.广播机制

In [37]:
arr1=np.random.randn(5)  #秩为1的数组
vec1=np.random.randn(5,1) #一个列向量
print(arr1,arr1.shape,arr1.T)
print(vec1,vec1.shape,vec1.T)
print("arr version:",np.dot(arr1,arr1.T))
print("vec version:",np.dot(vec1,vec1.T))

[-1.75029942  0.32400892  0.50432349  0.41262847  0.58807641] (5,) [-1.75029942  0.32400892  0.50432349  0.41262847  0.58807641]
[[-0.57093251]
 [-0.94384091]
 [-1.38145624]
 [-0.74570431]
 [-0.22009018]] (5, 1) [[-0.57093251 -0.94384091 -1.38145624 -0.74570431 -0.22009018]]
arr version: 3.938968152052318
vec version: [[0.32596393 0.53886946 0.78871827 0.42574683 0.12565664]
 [0.53886946 0.89083567 1.30387492 0.70382624 0.20773012]
 [0.78871827 1.30387492 1.90842135 1.03015787 0.30404495]
 [0.42574683 0.70382624 1.03015787 0.55607492 0.1641222 ]
 [0.12565664 0.20773012 0.30404495 0.1641222  0.04843969]]


In [46]:
# 最好是加上断言函数，减少一些不必要的bug
# assert(arr1.shape== (5,1)) #会报错
assert(vec1.shape== (5,1)) 