In [2]:
import  numpy as np

a3=np.random.randn(5,1)
print(a3)

[[-0.02146424]
 [ 0.69833023]
 [ 0.30825922]
 [ 0.06722775]
 [-0.87480704]]


In [3]:
d3 = np.random.rand(a3.shape[0],a3.shape[1])
print(d3)

[[0.37548556]
 [0.33612011]
 [0.79730368]
 [0.99878049]
 [0.82204526]]


# 将隐藏层中的单元按照概率随机置零

In [9]:
keep_prob=0.8
d3 = np.random.rand(a3.shape[0],a3.shape[1])<keep_prob
print(d3)

[[ True]
 [ True]
 [ True]
 [False]
 [ True]]


# 第三层中获取激活函数

In [11]:
a3=np.multiply(a3,d3)
print(a3)

[[-0.02146424]
 [ 0.69833023]
 [ 0.30825922]
 [ 0.        ]
 [-0.87480704]]


# 为了不影响期望值，进行数据的还原

In [12]:
a3/=keep_prob
print(a3)

[[-0.0268303 ]
 [ 0.87291279]
 [ 0.38532403]
 [ 0.        ]
 [-1.0935088 ]]
